# Generated by Django 4.2 on 2023-04-29 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
            ],
        ),
    ]
