# Generated by Django 4.2 on 2023-04-30 05:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0006_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, null=True), size=None),
        ),
    ]
