# Generated by Django 4.2 on 2023-05-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0009_remove_customer_allergens_customer_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish_id',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='menus', to='algapp.dishes'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_id',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='menus', to='algapp.restaurant'),
        ),
    ]
