# Generated by Django 4.2 on 2023-06-27 07:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0014_restaurant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='dish',
            new_name='dish_main_ings',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_var_ings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=250, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
