# Generated by Django 4.2 on 2023-06-27 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0015_rename_dish_dishes_dish_main_ings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_var_ings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=250, null=True), size=None),
        ),
    ]
