# Generated by Django 4.2 on 2023-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0017_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishesIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('dish_main_ingredients', models.ManyToManyField(related_name='main_dishes', to='algapp.ingredients')),
                ('dish_var_ingredients', models.ManyToManyField(related_name='var_dishes', to='algapp.ingredients')),
            ],
        ),
    ]
