# Generated by Django 4.2 on 2023-07-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algapp', '0022_alter_dishesing_dish_var_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesing',
            name='dish_var_ingredients',
            field=models.ManyToManyField(related_name='var_dishes', to='algapp.ingredients'),
        ),
    ]
